apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: prod-jenkins
  #  namespace: jenkins-operator
spec:
  service:
    type: LoadBalancer
    port: 8080
#  configurationAsCode:
#    configurations: 
#    - name: jenkins-operator-user-configuration
#    secret:
#      name: jenkins-conf-secrets
#  groovyScripts:
#    configurations:
#    - name: jenkins-operator-user-configuration
#    secret:
#      name: jenkins-conf-secrets
  configurationAsCode:
    configurations: []
    secret:
      name: ""
  groovyScripts:
    configurations: []
    secret:
      name: ""
  jenkinsAPISettings:
    authorizationStrategy: createUser
  master:
    disableCSRFProtection: false
#    basePlugins:
#    - name: kubernetes
#      version: "1.30.11"
#    - name: workflow-job
#      version: "1145.v7f2433caa07f"
#    - name: workflow-aggregator
#      version: "2.6"
#    - name: git
#      version: "4.10.0"
#    - name: job-dsl
#      version: "1.78.1"
#    - name: configuration-as-code
#      version: "1414.v878271fc496f"
#    - name: kubernetes-credentials-provider
#      version: "0.20"
#    plugins:
#    - name: cloudbees-folder
#      version: "6.800.v71307ca_b_986b"
#    - name: timestamper
#      version: "1.21"
#    - name: gradle
#      version: "2.2"
#    - name: ssh-slaves
#      version: "2.854.v7fd446b_337c9"
#    - name: github-branch-source
#      version: "1701.v00cc8184df93"
#    - name: ws-cleanup
#      version: "0.44"
#    - name: antisamy-markup-formatter
#      version: "155.v795fb_8702324"
#    - name: build-timeout
#      version: "1.28"
#    - name: pipeline-github-lib
#      version: "38.v445716ea_edda_"
#    - name: matrix-auth
#      version: "3.1.6"
#    - name: authorize-project
#      version: "1.4.0"
#    - name: credentials-binding
#      version: "523.vd859a_4b_122e6"
#    - name: pipeline-stage-view
#      version: "2.30"
#    - name: pam-auth
#      version: "1.10"
#    - name: mailer
#      version: "438.v02c7f0a_12fa_4"
#    - name: pipeline-milestone-step
#      version: "111.v449306f708b_7"
#    - name: pipeline-build-step
#      version: "2.18"
#    - name: pipeline-model-api
#      version: "2.2118.v31fd5b_9944b_5"
#    - name: pipeline-model-extensions
#      version: "2.2118.v31fd5b_9944b_5"
#    - name: workflow-multibranch
#      version: "716.vc692a_e52371b_"
#    - name: pipeline-stage-tags-metadata
#      version: "2.2118.v31fd5b_9944b_5"
#    - name: pipeline-model-definition
#      version: "2.2118.v31fd5b_9944b_5"
#    - name: pipeline-stage-step
#      version: "305.ve96d0205c1c6"
#    - name: pipeline-build-step
#      version: "2.18"
#    - name: basic-branch-build-strategies
#      version: "71.vc1421f89888e"
    containers:
    - name: jenkins-master
      image: jenkins/jenkins:2.375.3-lts-alpine
#      image: 
      env:
      - name: DEBUG_JENKINS_OPERATOR
        value: "true"
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 12
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 100
        periodSeconds: 20
        successThreshold: 1
        timeoutSeconds: 15
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 500Mi
#      env:
#        DEBUG_JENKINS_OPERATOR: "true"
#      securityContext:
#        runAsUser: 1000
#        fsGroup: 1000
  seedJobs:
  - id: jenkins-operator
    targets: "cicd/jobs/*.jenkins"
    description: "Jenkins Operator repository"
    repositoryBranch: jenkins_operator
    repositoryUrl: https://github.com/pavan-kumar-99/vault-k8s.git
